Web/Controllers/HomeController.cs
using System.Linq;
using System.Web.Mvc;
using Services.Interfaces;
using Web.App;

namespace Web.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public ITransactionService TransactionService { get; set; }

        public ActionResult Index()
        {
            var transactions = TransactionService.GetTransactionsByUserId(CurrentUser.Get().Id).ToArray();
            return View(transactions);
        }
    }
}

Web/Controllers/TransactionController.cs
using System.Web.Mvc;
using Services.Interfaces;
using Web.App;
using Web.Models.Transaction;

namespace Web.Controllers
{
    public class TransactionController : Controller
    {
        public IUserService UserService { get; set; }
        public ITransactionService TransactionService { get; set; }

        public ActionResult CreateTransaction()
        {
            var recipients = UserService.GetAllRecipients(CurrentUser.Get().Id);

            var model = new CreateTransactionModel { recipients = recipients };

            return View("Create", model);
        }

        [HttpPost]
        public ActionResult CreateTransaction(CreateTransactionModel m)
        {
            var user = CurrentUser.Get();
            m.recipients = UserService.GetAllRecipients(user.Id);

            if (!ModelState.IsValid)
                return View("Create", m);

            if (m.Sum >= user.Balance)
            {
                ModelState.AddModelError("Sum", "Сумма к отправке превышает Ваш баланс");
                return View("Create", m);
            }

            TransactionService.CreateTransaction(user.Id, m.SelectedrecipientId, m.Sum);

            return RedirectToAction("Index", "Home");
        }

        public ActionResult CopyTransaction(int transactId)
        {
            var userId = CurrentUser.Get().Id;
            var recipients = UserService.GetAllRecipients(userId);
            var transaction = TransactionService.GetTransaction(transactId);

            var model = new CreateTransactionModel()
            {
                recipients = recipients,
                SelectedrecipientId = transaction.RecipientId,
                Sum = transaction.Sum
            };

            return View("Create", model);
        }

        [HttpPost]
        public ActionResult CopyTransaction(CreateTransactionModel m)
        {
            var user = CurrentUser.Get();
            m.recipients = UserService.GetAllRecipients(user.Id);

            if (!ModelState.IsValid)
                return View("Create", m);

            if (m.Sum >= user.Balance)
            {
                ModelState.AddModelError("Sum", "Сумма к отправке превышает Ваш баланс");
                return View("Create", m);
            }

            TransactionService.CreateTransaction(user.Id, m.SelectedrecipientId, m.Sum);

            return RedirectToAction("Index", "Home");
        }
    }
}

Web/Views/Home/Index.cshtml
@using Common
@using Services.Interfaces
@using Web.App
@model IEnumerable<Data.Entities.Transaction>
    
@{
    var user = CurrentUser.Get();
    var isAutentificated = !user.IsAnonymous();
    var userService = ServiceLocator.Get<IUserService>();
}

<style>
    td {
        padding: 5px 50px 0 0 !important;
    }
</style>

@if (isAutentificated)
{
    <br />
    <h3>
        @Html.ActionLink("Создать транзакцию", "CreateTransaction", "Transaction")
    </h3>
    <br />
    if (Model.Any())
    {
        <table>
            <thead>
                <tr style="font-size:16px;">
                    <td>Дата создания</td>
                    <td>Отправитель</td>
                    <td>Получатель</td>
                    <td>Сумма перевода</td>
                    <td>Баланс</td>
                </tr>
            </thead>
            @foreach (var transact in Model.OrderByDescending(t => t.CreatedAt))
            {
                <tr>
                    @{
                        var recipient = userService.GetUserById(transact.RecipientId);
                        var respondent = userService.GetUserById(transact.SenderId);
                    }
                    <td>@transact.CreatedAt</td>
                    <td>@respondent.FullName</td>
                    <td>@recipient.FullName</td>
                    @if (user.Id == transact.RecipientId)
                    {
                        <td>+ @transact.Sum</td>
                        <td>@transact.RecipientBalanceAfter</td>
                    }
                    else
                    {
                        <td>- @transact.Sum</td>
                        <td>@transact.SenderBalanceAfter</td>
                        <td>@Html.ActionLink("Повторить", "CopyTransaction", "Transaction", new { transactId = transact.Id }, null)</td>
                    }

                </tr>
                        }
        </table>
                        }
                        else
                        {
                            <div>
                                Не совершено ни одной операции
                            </div>
                            }
                        }
                        else
                        {
                            <div style="padding-top: 20px;">Для начала работы необходимо @Html.ActionLink("зарегистрироваться", "Register", "Account")</div>
                        }